<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.AccountsResponse</code>.
 */
class AccountsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .walletrpc.AccountsResponse.Account accounts = 1;</code>.
     */
    private $accounts;
    /**
     * Generated from protobuf field <code>bytes current_block_hash = 2;</code>.
     */
    private $current_block_hash = '';
    /**
     * Generated from protobuf field <code>int32 current_block_height = 3;</code>.
     */
    private $current_block_height = 0;

    public function __construct()
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .walletrpc.AccountsResponse.Account accounts = 1;</code>.
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAccounts()
    {
        return $this->accounts;
    }

    /**
     * Generated from protobuf field <code>repeated .walletrpc.AccountsResponse.Account accounts = 1;</code>.
     *
     * @param \Walletrpc\AccountsResponse_Account[]|\Google\Protobuf\Internal\RepeatedField $var
     *
     * @return $this
     */
    public function setAccounts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Walletrpc\AccountsResponse_Account::class);
        $this->accounts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes current_block_hash = 2;</code>.
     *
     * @return string
     */
    public function getCurrentBlockHash()
    {
        return $this->current_block_hash;
    }

    /**
     * Generated from protobuf field <code>bytes current_block_hash = 2;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setCurrentBlockHash($var)
    {
        GPBUtil::checkString($var, false);
        $this->current_block_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 current_block_height = 3;</code>.
     *
     * @return int
     */
    public function getCurrentBlockHeight()
    {
        return $this->current_block_height;
    }

    /**
     * Generated from protobuf field <code>int32 current_block_height = 3;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setCurrentBlockHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->current_block_height = $var;

        return $this;
    }
}
