<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

/**
 * Protobuf enum <code>Walletrpc\ChangePassphraseRequest\Key</code>.
 */
class ChangePassphraseRequest_Key
{
    /**
     * Generated from protobuf enum <code>PRIVATE = 0;</code>.
     */
    const PRIVATE = 0;
    /**
     * Generated from protobuf enum <code>PUBLIC = 1;</code>.
     */
    const PUBLIC = 1;
}
