<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.CreateWalletRequest</code>.
 */
class CreateWalletRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes public_passphrase = 1;</code>.
     */
    private $public_passphrase = '';
    /**
     * Generated from protobuf field <code>bytes private_passphrase = 2;</code>.
     */
    private $private_passphrase = '';
    /**
     * Generated from protobuf field <code>bytes seed = 3;</code>.
     */
    private $seed = '';

    public function __construct()
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes public_passphrase = 1;</code>.
     *
     * @return string
     */
    public function getPublicPassphrase()
    {
        return $this->public_passphrase;
    }

    /**
     * Generated from protobuf field <code>bytes public_passphrase = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setPublicPassphrase($var)
    {
        GPBUtil::checkString($var, false);
        $this->public_passphrase = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes private_passphrase = 2;</code>.
     *
     * @return string
     */
    public function getPrivatePassphrase()
    {
        return $this->private_passphrase;
    }

    /**
     * Generated from protobuf field <code>bytes private_passphrase = 2;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setPrivatePassphrase($var)
    {
        GPBUtil::checkString($var, false);
        $this->private_passphrase = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes seed = 3;</code>.
     *
     * @return string
     */
    public function getSeed()
    {
        return $this->seed;
    }

    /**
     * Generated from protobuf field <code>bytes seed = 3;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSeed($var)
    {
        GPBUtil::checkString($var, false);
        $this->seed = $var;

        return $this;
    }
}
