<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.FundTransactionRequest</code>
 */
class FundTransactionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 account = 1;</code>
     */
    private $account = 0;
    /**
     * Generated from protobuf field <code>int64 target_amount = 2;</code>
     */
    private $target_amount = 0;
    /**
     * Generated from protobuf field <code>int32 required_confirmations = 3;</code>
     */
    private $required_confirmations = 0;
    /**
     * Generated from protobuf field <code>bool include_immature_coinbases = 4;</code>
     */
    private $include_immature_coinbases = false;
    /**
     * Generated from protobuf field <code>bool include_change_script = 5;</code>
     */
    private $include_change_script = false;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 account = 1;</code>
     * @return int
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>uint32 account = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkUint32($var);
        $this->account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 target_amount = 2;</code>
     * @return int|string
     */
    public function getTargetAmount()
    {
        return $this->target_amount;
    }

    /**
     * Generated from protobuf field <code>int64 target_amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTargetAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->target_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 required_confirmations = 3;</code>
     * @return int
     */
    public function getRequiredConfirmations()
    {
        return $this->required_confirmations;
    }

    /**
     * Generated from protobuf field <code>int32 required_confirmations = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRequiredConfirmations($var)
    {
        GPBUtil::checkInt32($var);
        $this->required_confirmations = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool include_immature_coinbases = 4;</code>
     * @return bool
     */
    public function getIncludeImmatureCoinbases()
    {
        return $this->include_immature_coinbases;
    }

    /**
     * Generated from protobuf field <code>bool include_immature_coinbases = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeImmatureCoinbases($var)
    {
        GPBUtil::checkBool($var);
        $this->include_immature_coinbases = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool include_change_script = 5;</code>
     * @return bool
     */
    public function getIncludeChangeScript()
    {
        return $this->include_change_script;
    }

    /**
     * Generated from protobuf field <code>bool include_change_script = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeChangeScript($var)
    {
        GPBUtil::checkBool($var);
        $this->include_change_script = $var;

        return $this;
    }

}

