<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.FundTransactionResponse.PreviousOutput</code>.
 */
class FundTransactionResponse_PreviousOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes transaction_hash = 1;</code>.
     */
    private $transaction_hash = '';
    /**
     * Generated from protobuf field <code>uint32 output_index = 2;</code>.
     */
    private $output_index = 0;
    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>.
     */
    private $amount = 0;
    /**
     * Generated from protobuf field <code>bytes pk_script = 4;</code>.
     */
    private $pk_script = '';
    /**
     * Generated from protobuf field <code>int64 receive_time = 5;</code>.
     */
    private $receive_time = 0;
    /**
     * Generated from protobuf field <code>bool from_coinbase = 6;</code>.
     */
    private $from_coinbase = false;

    public function __construct()
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes transaction_hash = 1;</code>.
     *
     * @return string
     */
    public function getTransactionHash()
    {
        return $this->transaction_hash;
    }

    /**
     * Generated from protobuf field <code>bytes transaction_hash = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setTransactionHash($var)
    {
        GPBUtil::checkString($var, false);
        $this->transaction_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 output_index = 2;</code>.
     *
     * @return int
     */
    public function getOutputIndex()
    {
        return $this->output_index;
    }

    /**
     * Generated from protobuf field <code>uint32 output_index = 2;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setOutputIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->output_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>.
     *
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>.
     *
     * @param int|string $var
     *
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes pk_script = 4;</code>.
     *
     * @return string
     */
    public function getPkScript()
    {
        return $this->pk_script;
    }

    /**
     * Generated from protobuf field <code>bytes pk_script = 4;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setPkScript($var)
    {
        GPBUtil::checkString($var, false);
        $this->pk_script = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 receive_time = 5;</code>.
     *
     * @return int|string
     */
    public function getReceiveTime()
    {
        return $this->receive_time;
    }

    /**
     * Generated from protobuf field <code>int64 receive_time = 5;</code>.
     *
     * @param int|string $var
     *
     * @return $this
     */
    public function setReceiveTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->receive_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool from_coinbase = 6;</code>.
     *
     * @return bool
     */
    public function getFromCoinbase()
    {
        return $this->from_coinbase;
    }

    /**
     * Generated from protobuf field <code>bool from_coinbase = 6;</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setFromCoinbase($var)
    {
        GPBUtil::checkBool($var);
        $this->from_coinbase = $var;

        return $this;
    }
}
