<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

/**
 * Protobuf enum <code>Walletrpc\NextAddressRequest\Kind</code>.
 */
class NextAddressRequest_Kind
{
    /**
     * Generated from protobuf enum <code>BIP0044_EXTERNAL = 0;</code>.
     */
    const BIP0044_EXTERNAL = 0;
    /**
     * Generated from protobuf enum <code>BIP0044_INTERNAL = 1;</code>.
     */
    const BIP0044_INTERNAL = 1;
}
