<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.NextAddressResponse</code>.
 */
class NextAddressResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address = 1;</code>.
     */
    private $address = '';

    public function __construct()
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>.
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, true);
        $this->address = $var;

        return $this;
    }
}
