<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.OpenWalletRequest</code>
 */
class OpenWalletRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes public_passphrase = 1;</code>
     */
    private $public_passphrase = '';

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes public_passphrase = 1;</code>
     * @return string
     */
    public function getPublicPassphrase()
    {
        return $this->public_passphrase;
    }

    /**
     * Generated from protobuf field <code>bytes public_passphrase = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicPassphrase($var)
    {
        GPBUtil::checkString($var, False);
        $this->public_passphrase = $var;

        return $this;
    }

}

