<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.PublishTransactionResponse</code>
 */
class PublishTransactionResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

}

