<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.PublishTransactionRequest</code>.
 */
class PublishTransactionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes signed_transaction = 1;</code>.
     */
    private $signed_transaction = '';

    public function __construct()
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes signed_transaction = 1;</code>.
     *
     * @return string
     */
    public function getSignedTransaction()
    {
        return $this->signed_transaction;
    }

    /**
     * Generated from protobuf field <code>bytes signed_transaction = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSignedTransaction($var)
    {
        GPBUtil::checkString($var, false);
        $this->signed_transaction = $var;

        return $this;
    }
}
