<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.SignTransactionResponse</code>.
 */
class SignTransactionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes transaction = 1;</code>.
     */
    private $transaction = '';
    /**
     * Generated from protobuf field <code>repeated uint32 unsigned_input_indexes = 2;</code>.
     */
    private $unsigned_input_indexes;

    public function __construct()
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes transaction = 1;</code>.
     *
     * @return string
     */
    public function getTransaction()
    {
        return $this->transaction;
    }

    /**
     * Generated from protobuf field <code>bytes transaction = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setTransaction($var)
    {
        GPBUtil::checkString($var, false);
        $this->transaction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 unsigned_input_indexes = 2;</code>.
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnsignedInputIndexes()
    {
        return $this->unsigned_input_indexes;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 unsigned_input_indexes = 2;</code>.
     *
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     *
     * @return $this
     */
    public function setUnsignedInputIndexes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->unsigned_input_indexes = $arr;

        return $this;
    }
}
