<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.SignTransactionRequest</code>.
 */
class SignTransactionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes passphrase = 1;</code>.
     */
    private $passphrase = '';
    /**
     * Generated from protobuf field <code>bytes serialized_transaction = 2;</code>.
     */
    private $serialized_transaction = '';
    /**
     * If no indexes are specified, signatures scripts will be added for
     * every input. If any input indexes are specified, only those inputs
     * will be signed.  Rather than returning an incompletely signed
     * transaction if any of the inputs to be signed can not be, the RPC
     * immediately errors.
     *
     * Generated from protobuf field <code>repeated uint32 input_indexes = 3;</code>
     */
    private $input_indexes;

    public function __construct()
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes passphrase = 1;</code>.
     *
     * @return string
     */
    public function getPassphrase()
    {
        return $this->passphrase;
    }

    /**
     * Generated from protobuf field <code>bytes passphrase = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setPassphrase($var)
    {
        GPBUtil::checkString($var, false);
        $this->passphrase = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes serialized_transaction = 2;</code>.
     *
     * @return string
     */
    public function getSerializedTransaction()
    {
        return $this->serialized_transaction;
    }

    /**
     * Generated from protobuf field <code>bytes serialized_transaction = 2;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSerializedTransaction($var)
    {
        GPBUtil::checkString($var, false);
        $this->serialized_transaction = $var;

        return $this;
    }

    /**
     * If no indexes are specified, signatures scripts will be added for
     * every input. If any input indexes are specified, only those inputs
     * will be signed.  Rather than returning an incompletely signed
     * transaction if any of the inputs to be signed can not be, the RPC
     * immediately errors.
     *
     * Generated from protobuf field <code>repeated uint32 input_indexes = 3;</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInputIndexes()
    {
        return $this->input_indexes;
    }

    /**
     * If no indexes are specified, signatures scripts will be added for
     * every input. If any input indexes are specified, only those inputs
     * will be signed.  Rather than returning an incompletely signed
     * transaction if any of the inputs to be signed can not be, the RPC
     * immediately errors.
     *
     * Generated from protobuf field <code>repeated uint32 input_indexes = 3;</code>
     *
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     *
     * @return $this
     */
    public function setInputIndexes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->input_indexes = $arr;

        return $this;
    }
}
