<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.SpentnessNotificationsResponse</code>
 */
class SpentnessNotificationsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes transaction_hash = 1;</code>
     */
    private $transaction_hash = '';
    /**
     * Generated from protobuf field <code>uint32 output_index = 2;</code>
     */
    private $output_index = 0;
    /**
     * Generated from protobuf field <code>.walletrpc.SpentnessNotificationsResponse.Spender spender = 3;</code>
     */
    private $spender = null;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes transaction_hash = 1;</code>
     * @return string
     */
    public function getTransactionHash()
    {
        return $this->transaction_hash;
    }

    /**
     * Generated from protobuf field <code>bytes transaction_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->transaction_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 output_index = 2;</code>
     * @return int
     */
    public function getOutputIndex()
    {
        return $this->output_index;
    }

    /**
     * Generated from protobuf field <code>uint32 output_index = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOutputIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->output_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.walletrpc.SpentnessNotificationsResponse.Spender spender = 3;</code>
     * @return \Walletrpc\SpentnessNotificationsResponse_Spender
     */
    public function getSpender()
    {
        return $this->spender;
    }

    /**
     * Generated from protobuf field <code>.walletrpc.SpentnessNotificationsResponse.Spender spender = 3;</code>
     * @param \Walletrpc\SpentnessNotificationsResponse_Spender $var
     * @return $this
     */
    public function setSpender($var)
    {
        GPBUtil::checkMessage($var, \Walletrpc\SpentnessNotificationsResponse_Spender::class);
        $this->spender = $var;

        return $this;
    }

}

