<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.SpentnessNotificationsResponse.Spender</code>.
 */
class SpentnessNotificationsResponse_Spender extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes transaction_hash = 1;</code>.
     */
    private $transaction_hash = '';
    /**
     * Generated from protobuf field <code>uint32 input_index = 2;</code>.
     */
    private $input_index = 0;

    public function __construct()
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes transaction_hash = 1;</code>.
     *
     * @return string
     */
    public function getTransactionHash()
    {
        return $this->transaction_hash;
    }

    /**
     * Generated from protobuf field <code>bytes transaction_hash = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setTransactionHash($var)
    {
        GPBUtil::checkString($var, false);
        $this->transaction_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 input_index = 2;</code>.
     *
     * @return int
     */
    public function getInputIndex()
    {
        return $this->input_index;
    }

    /**
     * Generated from protobuf field <code>uint32 input_index = 2;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setInputIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->input_index = $var;

        return $this;
    }
}
