<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.StartConsensusRpcRequest</code>.
 */
class StartConsensusRpcRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string network_address = 1;</code>.
     */
    private $network_address = '';
    /**
     * Generated from protobuf field <code>string username = 2;</code>.
     */
    private $username = '';
    /**
     * Generated from protobuf field <code>bytes password = 3;</code>.
     */
    private $password = '';
    /**
     * Generated from protobuf field <code>bytes certificate = 4;</code>.
     */
    private $certificate = '';

    public function __construct()
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string network_address = 1;</code>.
     *
     * @return string
     */
    public function getNetworkAddress()
    {
        return $this->network_address;
    }

    /**
     * Generated from protobuf field <code>string network_address = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setNetworkAddress($var)
    {
        GPBUtil::checkString($var, true);
        $this->network_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>.
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, true);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes password = 3;</code>.
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>bytes password = 3;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, false);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes certificate = 4;</code>.
     *
     * @return string
     */
    public function getCertificate()
    {
        return $this->certificate;
    }

    /**
     * Generated from protobuf field <code>bytes certificate = 4;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setCertificate($var)
    {
        GPBUtil::checkString($var, false);
        $this->certificate = $var;

        return $this;
    }
}
