<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.TransactionDetails.Input</code>.
 */
class TransactionDetails_Input extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 index = 1;</code>.
     */
    private $index = 0;
    /**
     * Generated from protobuf field <code>uint32 previous_account = 2;</code>.
     */
    private $previous_account = 0;
    /**
     * Generated from protobuf field <code>int64 previous_amount = 3;</code>.
     */
    private $previous_amount = 0;

    public function __construct()
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 index = 1;</code>.
     *
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>uint32 index = 1;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 previous_account = 2;</code>.
     *
     * @return int
     */
    public function getPreviousAccount()
    {
        return $this->previous_account;
    }

    /**
     * Generated from protobuf field <code>uint32 previous_account = 2;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setPreviousAccount($var)
    {
        GPBUtil::checkUint32($var);
        $this->previous_account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 previous_amount = 3;</code>.
     *
     * @return int|string
     */
    public function getPreviousAmount()
    {
        return $this->previous_amount;
    }

    /**
     * Generated from protobuf field <code>int64 previous_amount = 3;</code>.
     *
     * @param int|string $var
     *
     * @return $this
     */
    public function setPreviousAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->previous_amount = $var;

        return $this;
    }
}
