<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.TransactionDetails.Output</code>.
 */
class TransactionDetails_Output extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 index = 1;</code>.
     */
    private $index = 0;
    /**
     * Generated from protobuf field <code>uint32 account = 2;</code>.
     */
    private $account = 0;
    /**
     * Generated from protobuf field <code>bool internal = 3;</code>.
     */
    private $internal = false;

    public function __construct()
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 index = 1;</code>.
     *
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>uint32 index = 1;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 account = 2;</code>.
     *
     * @return int
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>uint32 account = 2;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkUint32($var);
        $this->account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool internal = 3;</code>.
     *
     * @return bool
     */
    public function getInternal()
    {
        return $this->internal;
    }

    /**
     * Generated from protobuf field <code>bool internal = 3;</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setInternal($var)
    {
        GPBUtil::checkBool($var);
        $this->internal = $var;

        return $this;
    }
}
