<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

/**
 * Generated from protobuf message <code>walletrpc.VersionRequest</code>.
 */
class VersionRequest extends \Google\Protobuf\Internal\Message
{
    public function __construct()
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }
}
