<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

final class VersionServiceServiceStub implements VersionServiceService
{
    use \Lv\Grpc\CurlStubTrait;

    public function Version(\Walletrpc\VersionRequest $request) : \Walletrpc\VersionResponse
    {
        $reply = new \Walletrpc\VersionResponse();

        $this->send('/walletrpc.VersionService/Version', $request, $reply);

        return $reply;
    }
}
