<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.VersionResponse</code>.
 */
class VersionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string version_string = 1;</code>.
     */
    private $version_string = '';
    /**
     * Generated from protobuf field <code>uint32 major = 2;</code>.
     */
    private $major = 0;
    /**
     * Generated from protobuf field <code>uint32 minor = 3;</code>.
     */
    private $minor = 0;
    /**
     * Generated from protobuf field <code>uint32 patch = 4;</code>.
     */
    private $patch = 0;
    /**
     * Generated from protobuf field <code>string prerelease = 5;</code>.
     */
    private $prerelease = '';
    /**
     * Generated from protobuf field <code>string build_metadata = 6;</code>.
     */
    private $build_metadata = '';

    public function __construct()
    {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string version_string = 1;</code>.
     *
     * @return string
     */
    public function getVersionString()
    {
        return $this->version_string;
    }

    /**
     * Generated from protobuf field <code>string version_string = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setVersionString($var)
    {
        GPBUtil::checkString($var, true);
        $this->version_string = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 major = 2;</code>.
     *
     * @return int
     */
    public function getMajor()
    {
        return $this->major;
    }

    /**
     * Generated from protobuf field <code>uint32 major = 2;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setMajor($var)
    {
        GPBUtil::checkUint32($var);
        $this->major = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 minor = 3;</code>.
     *
     * @return int
     */
    public function getMinor()
    {
        return $this->minor;
    }

    /**
     * Generated from protobuf field <code>uint32 minor = 3;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setMinor($var)
    {
        GPBUtil::checkUint32($var);
        $this->minor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 patch = 4;</code>.
     *
     * @return int
     */
    public function getPatch()
    {
        return $this->patch;
    }

    /**
     * Generated from protobuf field <code>uint32 patch = 4;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setPatch($var)
    {
        GPBUtil::checkUint32($var);
        $this->patch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prerelease = 5;</code>.
     *
     * @return string
     */
    public function getPrerelease()
    {
        return $this->prerelease;
    }

    /**
     * Generated from protobuf field <code>string prerelease = 5;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setPrerelease($var)
    {
        GPBUtil::checkString($var, true);
        $this->prerelease = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string build_metadata = 6;</code>.
     *
     * @return string
     */
    public function getBuildMetadata()
    {
        return $this->build_metadata;
    }

    /**
     * Generated from protobuf field <code>string build_metadata = 6;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setBuildMetadata($var)
    {
        GPBUtil::checkString($var, true);
        $this->build_metadata = $var;

        return $this;
    }
}
