<?php
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

interface VersionServiceService extends \Lv\Grpc\Service
{
    function Version(\Walletrpc\VersionRequest $request) : \Walletrpc\VersionResponse;
}
