<?php
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

interface WalletLoaderServiceService extends \Lv\Grpc\Service
{
    function WalletExists(\Walletrpc\WalletExistsRequest $request) : \Walletrpc\WalletExistsResponse;
    function CreateWallet(\Walletrpc\CreateWalletRequest $request) : \Walletrpc\CreateWalletResponse;
    function OpenWallet(\Walletrpc\OpenWalletRequest $request) : \Walletrpc\OpenWalletResponse;
    function CloseWallet(\Walletrpc\CloseWalletRequest $request) : \Walletrpc\CloseWalletResponse;
    function StartConsensusRpc(\Walletrpc\StartConsensusRpcRequest $request) : \Walletrpc\StartConsensusRpcResponse;
}
