<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

interface WalletLoaderServiceService extends \Lv\Grpc\Service
{
    public function WalletExists(\Walletrpc\WalletExistsRequest $request) : \Walletrpc\WalletExistsResponse;

    public function CreateWallet(\Walletrpc\CreateWalletRequest $request) : \Walletrpc\CreateWalletResponse;

    public function OpenWallet(\Walletrpc\OpenWalletRequest $request) : \Walletrpc\OpenWalletResponse;

    public function CloseWallet(\Walletrpc\CloseWalletRequest $request) : \Walletrpc\CloseWalletResponse;

    public function StartConsensusRpc(\Walletrpc\StartConsensusRpcRequest $request) : \Walletrpc\StartConsensusRpcResponse;
}
