<?php
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

interface WalletServiceService extends \Lv\Grpc\Service
{
    /**
     * Queries
     */
    function Ping(\Walletrpc\PingRequest $request) : \Walletrpc\PingResponse;
    function Network(\Walletrpc\NetworkRequest $request) : \Walletrpc\NetworkResponse;
    function AccountNumber(\Walletrpc\AccountNumberRequest $request) : \Walletrpc\AccountNumberResponse;
    function Accounts(\Walletrpc\AccountsRequest $request) : \Walletrpc\AccountsResponse;
    function Balance(\Walletrpc\BalanceRequest $request) : \Walletrpc\BalanceResponse;
    function GetTransactions(\Walletrpc\GetTransactionsRequest $request) : \Walletrpc\GetTransactionsResponse;
    /**
     * Notifications
     */
    function TransactionNotifications(\Walletrpc\TransactionNotificationsRequest $request) : \Walletrpc\TransactionNotificationsResponse;
    function SpentnessNotifications(\Walletrpc\SpentnessNotificationsRequest $request) : \Walletrpc\SpentnessNotificationsResponse;
    function AccountNotifications(\Walletrpc\AccountNotificationsRequest $request) : \Walletrpc\AccountNotificationsResponse;
    /**
     * Control
     */
    function ChangePassphrase(\Walletrpc\ChangePassphraseRequest $request) : \Walletrpc\ChangePassphraseResponse;
    function RenameAccount(\Walletrpc\RenameAccountRequest $request) : \Walletrpc\RenameAccountResponse;
    function NextAccount(\Walletrpc\NextAccountRequest $request) : \Walletrpc\NextAccountResponse;
    function NextAddress(\Walletrpc\NextAddressRequest $request) : \Walletrpc\NextAddressResponse;
    function ImportPrivateKey(\Walletrpc\ImportPrivateKeyRequest $request) : \Walletrpc\ImportPrivateKeyResponse;
    function FundTransaction(\Walletrpc\FundTransactionRequest $request) : \Walletrpc\FundTransactionResponse;
    function SignTransaction(\Walletrpc\SignTransactionRequest $request) : \Walletrpc\SignTransactionResponse;
    function PublishTransaction(\Walletrpc\PublishTransactionRequest $request) : \Walletrpc\PublishTransactionResponse;
}
