<?php
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

final class WalletLoaderServiceServiceStub implements WalletLoaderServiceService
{
    use \Lv\Grpc\CurlStubTrait;

    public function WalletExists(\Walletrpc\WalletExistsRequest $request) : \Walletrpc\WalletExistsResponse
    {
        $reply = new \Walletrpc\WalletExistsResponse();

        $this->send("/walletrpc.WalletLoaderService/WalletExists", $request, $reply);

        return $reply;
    }
    public function CreateWallet(\Walletrpc\CreateWalletRequest $request) : \Walletrpc\CreateWalletResponse
    {
        $reply = new \Walletrpc\CreateWalletResponse();

        $this->send("/walletrpc.WalletLoaderService/CreateWallet", $request, $reply);

        return $reply;
    }
    public function OpenWallet(\Walletrpc\OpenWalletRequest $request) : \Walletrpc\OpenWalletResponse
    {
        $reply = new \Walletrpc\OpenWalletResponse();

        $this->send("/walletrpc.WalletLoaderService/OpenWallet", $request, $reply);

        return $reply;
    }
    public function CloseWallet(\Walletrpc\CloseWalletRequest $request) : \Walletrpc\CloseWalletResponse
    {
        $reply = new \Walletrpc\CloseWalletResponse();

        $this->send("/walletrpc.WalletLoaderService/CloseWallet", $request, $reply);

        return $reply;
    }
    public function StartConsensusRpc(\Walletrpc\StartConsensusRpcRequest $request) : \Walletrpc\StartConsensusRpcResponse
    {
        $reply = new \Walletrpc\StartConsensusRpcResponse();

        $this->send("/walletrpc.WalletLoaderService/StartConsensusRpc", $request, $reply);

        return $reply;
    }
}
