<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

namespace Walletrpc;

interface WalletServiceService extends \Lv\Grpc\Service
{
    /**
     * Queries.
     */
    public function Ping(\Walletrpc\PingRequest $request) : \Walletrpc\PingResponse;

    public function Network(\Walletrpc\NetworkRequest $request) : \Walletrpc\NetworkResponse;

    public function AccountNumber(\Walletrpc\AccountNumberRequest $request) : \Walletrpc\AccountNumberResponse;

    public function Accounts(\Walletrpc\AccountsRequest $request) : \Walletrpc\AccountsResponse;

    public function Balance(\Walletrpc\BalanceRequest $request) : \Walletrpc\BalanceResponse;

    public function GetTransactions(\Walletrpc\GetTransactionsRequest $request) : \Walletrpc\GetTransactionsResponse;

    /**
     * Notifications.
     */
    public function TransactionNotifications(\Walletrpc\TransactionNotificationsRequest $request) : \Walletrpc\TransactionNotificationsResponse;

    public function SpentnessNotifications(\Walletrpc\SpentnessNotificationsRequest $request) : \Walletrpc\SpentnessNotificationsResponse;

    public function AccountNotifications(\Walletrpc\AccountNotificationsRequest $request) : \Walletrpc\AccountNotificationsResponse;

    /**
     * Control.
     */
    public function ChangePassphrase(\Walletrpc\ChangePassphraseRequest $request) : \Walletrpc\ChangePassphraseResponse;

    public function RenameAccount(\Walletrpc\RenameAccountRequest $request) : \Walletrpc\RenameAccountResponse;

    public function NextAccount(\Walletrpc\NextAccountRequest $request) : \Walletrpc\NextAccountResponse;

    public function NextAddress(\Walletrpc\NextAddressRequest $request) : \Walletrpc\NextAddressResponse;

    public function ImportPrivateKey(\Walletrpc\ImportPrivateKeyRequest $request) : \Walletrpc\ImportPrivateKeyResponse;

    public function FundTransaction(\Walletrpc\FundTransactionRequest $request) : \Walletrpc\FundTransactionResponse;

    public function SignTransaction(\Walletrpc\SignTransactionRequest $request) : \Walletrpc\SignTransactionResponse;

    public function PublishTransaction(\Walletrpc\PublishTransactionRequest $request) : \Walletrpc\PublishTransactionResponse;
}
